### ISSUE TITLE
安装好后启动时一直提示文件不存在

### ISSUE THREAD

**Issue by buddingworld** [chenmozhijin/luci-app-socat#1]
Thu Nov  9 19:15:26 2023 daemon.err uhttpd[4186]: cat: can't open '/var/etc/socat.port': No such file or directory

如上，手动创建并不能使用

**Comment by chenmozhijin** [comment]
我自己在OpenWrt 23.05.0-rc4使用没有遇到这种情况，不能使用是一个什么不能使用法？
/var/etc/socat.port是记录要打开的防火墙端口用的，应该不会导致无法使用。

可以尝试终端运行
```
/etc/init.d/luci_socat restart
```
看看有什么输出

**Comment by Eugene-Zhou** [comment]
你好，我也碰到了一样的情况，
<img width="704" alt="image" src="https://github.com/chenmozhijin/luci-app-socat/assets/64573705/43101d39-685a-4b6d-aae4-a01f43fa39b7">
装完后就报这个错了：
<img width="712" alt="image" src="https://github.com/chenmozhijin/luci-app-socat/assets/64573705/cd760dcd-4f47-4152-a283-a0c3c8b6bd56">

**Comment by chenmozhijin** [comment]
> 你好，我也碰到了一样的情况，
> <img width="704" alt="image" src="https://github.com/chenmozhijin/luci-app-socat/assets/64573705/43101d39-685a-4b6d-aae4-a01f43fa39b7">
> 装完后就报这个错了：
> <img width="712" alt="image" src="https://github.com/chenmozhijin/luci-app-socat/assets/64573705/cd760dcd-4f47-4152-a283-a0c3c8b6bd56">
> 

有什么影响吗？比如什么功能不能用之类的？
