### ISSUE TITLE
 ImmortalWrt 安装问题

### ISSUE THREAD

**Issue by mitsukileung** [chenmozhijin/luci-app-socat#2]
在 ImmortalWrt 上删除原来的 luci-app-socat，安装上 luci-app-socat_20231117_all.ipk 和 luci-i18n-socat-zh-cn_231116.60682_all.ipk 后，菜单里没有显示，在SSH下输入 /etc/init.d/luci_socat restart 显示 not open firewall ports ，请问要怎样安装？

**Comment by chenmozhijin** [comment]
这是正常的吧，只是没有要打开防火墙端口的配置。

菜单里没有显示的话可以试试重启系统

**Comment by mitsukileung** [comment]
> 这是正常的吧，只是没有要打开防火墙端口的配置。

现成的安装包无法使用，但用源码编译进固件可以正常使用，谢谢！
