### ISSUE TITLE
20231117版本反馈

### ISSUE THREAD

**Issue by Eugene-Zhou** [chenmozhijin/luci-app-socat#3]
你好，我装了20231117版本的，安装成功，但是使用的时候如下图：
我的OpenWRT版本：23.05-SNAPSHOT，路由器型号：Netgear wndr4300v2

![image](https://github.com/chenmozhijin/luci-app-socat/assets/64573705/06674ea1-e652-48e4-9193-741ca3dff3fa)

**Comment by chenmozhijin** [comment]
应该是缺少了`luci-compat`这个依赖，装一下试试看

我已经把它加到v20231119的依赖列表了

**Comment by Eugene-Zhou** [comment]
哥们你好，装了luci-compat后socat成功运行起来了，非常感谢！

还有个问题需要咨询你，我的端口转发状态始终是红叉叉，不知道在哪里能看到开启失败的原因。控制台里也没有输出。

<img width="1047" alt="image" src="https://github.com/chenmozhijin/luci-app-socat/assets/64573705/8d854309-0fb8-4f5a-8b6e-15b1de3b32e2">

**Comment by chenmozhijin** [comment]
运行一下`/etc/init.d/luci_socat restart`看看

**Comment by Eugene-Zhou** [comment]
> 运行一下`/etc/init.d/luci_socat restart`看看

非常感谢！已经成功了～～
thanks very much! it works~~
ありがとうございます！できた～～

 就是每添加一条就要restart一次，点击“保存并应用”没有任何作用，到自启管理中点击“重启”或者“停止——启动”也没有作用。一定要用/etc/init.d/luci_socat restart才可以。

**Comment by chenmozhijin** [comment]
不应该呀,可能是[初始化的脚本](https://github.com/chenmozhijin/luci-app-socat/blob/main/luci-app-socat/root/etc/uci-defaults/luci-app-socat)没有运行，运行一下下面的命令看看。
```
uci -q batch <<-EOF >/dev/null
	delete firewall.socat
	set firewall.socat=include
	set firewall.socat.type=script
	set firewall.socat.path=/var/etc/socat.include
	set firewall.socat.reload=1
EOF

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@socat[-1]
	add ucitrack socat
	set ucitrack.@socat[-1].init=luci_socat
	commit ucitrack
EOF

rm -rf /tmp/luci-*cache
```

**Comment by roccocx** [comment]
大佬遇到了同样的问题，opennwrt官方固件每次添加都要/etc/init.d/luci_socat restart才会生效，执行了这个脚本但是没有起作用

**Comment by chenmozhijin** [comment]
> 大佬遇到了同样的问题，opennwrt官方固件每次添加都要/etc/init.d/luci_socat restart才会生效，执行了这个脚本但是没有起作用

点击"保存并应用"没有用吗？

我测试是正常的


https://github.com/chenmozhijin/luci-app-socat/assets/110812055/005d63d8-b668-426c-8810-1778f200d218

**Comment by lazyoop** [comment]
> > 大佬遇到了同样的问题，opennwrt官方固件每次添加都要/etc/init.d/luci_socat restart才会生效，执行了这个脚本但是没有起作用
> 
> 点击"保存并应用"没有用吗？
> 
> 我测试是正常的
> 
>  2023-12-2122-06-34.mp4

在 ImmortalWrt OpenWrt 24.10 ，「保存並應用」無效，需手動執行 /etc/init.d/luci_socat restart 才會生效。
