### ISSUE TITLE
请问这个socat的框架是iptables还是nftables

### ISSUE THREAD

**Issue by lrhwh** [chenmozhijin/luci-app-socat#4]
我用ImmortalWrt编译的固件，官方的socat插件虽然能用，但日志总是报错，官方的socat插件是基于iptables，但我编译的固件是基于nftables。所以我想找个基于nftables的socat插件。

**Comment by chenmozhijin** [comment]
直接调用的openwrt的防火墙

**Comment by lrhwh** [comment]
多谢！！！
使用你的socat插件，端口转发正常，系统日志不报错。
